# Generated by Django 6.0.5 on 2026-05-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название занятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)')),
                ('color', models.CharField(default='#4CAF50', max_length=20, verbose_name='Цвет в расписании')),
            ],
            options={
                'verbose_name': 'Вид занятия',
                'verbose_name_plural': 'Виды занятий',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО тренера')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('capacity', models.PositiveIntegerField(default=10, verbose_name='Вместимость')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.activity', verbose_name='Занятие')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Элемент расписания',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='schedule.schedule', verbose_name='Занятие в расписании')),
            ],
            options={
                'verbose_name': 'Запись на занятие',
                'verbose_name_plural': 'Записи на занятия',
                'unique_together': {('schedule', 'user')},
            },
        ),
    ]
