# Generated by Django 6.0.5 on 2026-05-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='freeze_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала заморозки'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Заморожен'),
        ),
    ]
